// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhaleApp.Models;

#nullable disable

namespace WhaleApp.Migrations
{
    [DbContext(typeof(WhaleContext))]
    [Migration("20241016201639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhaleApp.Models.ConservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Extinct"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Extinct in the Wild"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Critically Endangered"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Endangered"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vulnerable"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Near Threatened"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Least Concern"
                        });
                });

            modelBuilder.Entity("WhaleApp.Models.Whale", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConservationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInArcticOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAtlanticOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInIndianOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInPacificOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSouthernOcean")
                        .HasColumnType("bit");

                    b.Property<int?>("Lifespan")
                        .HasColumnType("int");

                    b.Property<int?>("MigrationDistance")
                        .HasColumnType("int");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConservationStatusId");

                    b.ToTable("Whales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommonName = "Blue whale",
                            ConservationStatusId = 2,
                            Description = "odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
                            IsInArcticOcean = true,
                            IsInAtlanticOcean = false,
                            IsInIndianOcean = true,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 241,
                            MigrationDistance = 874,
                            Population = 7270,
                            ScientificName = "Heloderma horridum"
                        },
                        new
                        {
                            Id = 2,
                            CommonName = "Humpback whale",
                            ConservationStatusId = 5,
                            Description = "integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 105,
                            MigrationDistance = 7575,
                            Population = 4143,
                            ScientificName = "Phalaropus lobatus"
                        },
                        new
                        {
                            Id = 3,
                            CommonName = "Fin whale",
                            ConservationStatusId = 3,
                            Description = "aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",
                            IsInArcticOcean = true,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = false,
                            IsInSouthernOcean = false,
                            Lifespan = 379,
                            MigrationDistance = 9548,
                            Population = 2956,
                            ScientificName = "Limosa haemastica"
                        },
                        new
                        {
                            Id = 4,
                            CommonName = "Beluga whale",
                            ConservationStatusId = 3,
                            Description = "aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = false,
                            IsInSouthernOcean = true,
                            Lifespan = 624,
                            MigrationDistance = 9180,
                            Population = 8286,
                            ScientificName = "Mycteria leucocephala"
                        },
                        new
                        {
                            Id = 5,
                            CommonName = "Sperm whale",
                            ConservationStatusId = 6,
                            Description = "morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = false,
                            IsInIndianOcean = false,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 957,
                            MigrationDistance = 5765,
                            Population = 831,
                            ScientificName = "Bassariscus astutus"
                        });
                });

            modelBuilder.Entity("WhaleApp.Models.Whale", b =>
                {
                    b.HasOne("WhaleApp.Models.ConservationStatus", "ConservationStatus")
                        .WithMany()
                        .HasForeignKey("ConservationStatusId");

                    b.Navigation("ConservationStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
