// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhaleApp.Models;

#nullable disable

namespace WhaleApp.Migrations
{
    [DbContext(typeof(WhaleContext))]
    partial class WhaleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhaleApp.Models.Whale", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInArcticOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAtlanticOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInIndianOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInPacificOcean")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSouthernOcean")
                        .HasColumnType("bit");

                    b.Property<int?>("Lifespan")
                        .HasColumnType("int");

                    b.Property<int?>("MigrationDistance")
                        .HasColumnType("int");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Whales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommonName = "Blue whale",
                            ConservationStatus = 2,
                            Description = "odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
                            IsInArcticOcean = true,
                            IsInAtlanticOcean = false,
                            IsInIndianOcean = true,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 241,
                            MigrationDistance = 874,
                            Population = 7270,
                            ScientificName = "Heloderma horridum"
                        },
                        new
                        {
                            Id = 2,
                            CommonName = "Humpback whale",
                            ConservationStatus = 5,
                            Description = "integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam\r\n",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 105,
                            MigrationDistance = 7575,
                            Population = 4143,
                            ScientificName = "Phalaropus lobatus"
                        },
                        new
                        {
                            Id = 3,
                            CommonName = "Fin whale",
                            ConservationStatus = 3,
                            Description = "aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam\r\n",
                            IsInArcticOcean = true,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = false,
                            IsInSouthernOcean = false,
                            Lifespan = 379,
                            MigrationDistance = 9548,
                            Population = 2956,
                            ScientificName = "Limosa haemastica"
                        },
                        new
                        {
                            Id = 4,
                            CommonName = "Beluga whale",
                            ConservationStatus = 3,
                            Description = "aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio\r\n",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = true,
                            IsInIndianOcean = true,
                            IsInPacificOcean = false,
                            IsInSouthernOcean = true,
                            Lifespan = 624,
                            MigrationDistance = 9180,
                            Population = 8286,
                            ScientificName = "Mycteria leucocephala"
                        },
                        new
                        {
                            Id = 5,
                            CommonName = "Sperm whale",
                            ConservationStatus = 6,
                            Description = "morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis\r\n",
                            IsInArcticOcean = false,
                            IsInAtlanticOcean = false,
                            IsInIndianOcean = false,
                            IsInPacificOcean = true,
                            IsInSouthernOcean = false,
                            Lifespan = 957,
                            MigrationDistance = 5765,
                            Population = 831,
                            ScientificName = "Bassariscus astutus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
